version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-project1  # Destination on your EC2 instance
hooks:
  AfterInstall:
    - location: install/install_dependencies.sh  # Update path if needed
      timeout: 300
      runas: root
  ApplicationStart:
    - location: install/start_server.sh
      timeout: 300
      runas: root
