version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myproject
hooks:
  BeforeInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
